symptom_check_task:
  description: |
    Analyze the following patient symptoms and suggest possible diagnoses based on medical guidelines.

    Context from medical knowledge base:
    {context}

    Use only the context above to answer. If unsure, say "Based on available guidelines, I cannot determine with certainty."
  expected_output: "List of possible conditions with likelihood indicators and supporting evidence from guidelines."
  agent: symptom_checker_agent

medical_history_task:
  description: |
    Retrieve patient medical history using the Patient Records Retrieval Tool.
    Use the patient_id if available. Summarize the most relevant medical records
    concisely and clearly for the user's query.
  expected_output: >
    Concise, readable answer for patient queries
  agent: medical_history_agent

appointment_booking_task:
  description: |
    Handle doctor appointment booking requests using the Appointment Booking Tool.
    
    Your responsibilities include:
    1. Extract appointment details from user requests (email, desired doctor, preferred time)
    2. Use the Appointment Booking Tool to check availability and book appointments
    3. Handle responses from the booking system appropriately:
       - For successful bookings: Confirm details and mention confirmation emails
       - For unavailable slots: Present alternative options clearly
       - For errors: Explain the issue and suggest next steps
    
    Key guidelines:
    - Always verify you have the required information (email, doctor name, preferred time)
    - Convert time references to ISO format (e.g., "Monday 10am" → "2025-09-16T10:00")
    - If information is missing, ask the user politely for clarification
    - Present appointment options in a user-friendly format
    - Maintain a professional and helpful tone throughout
    
    Remember: The booking system automatically handles availability checking, 
    conflict prevention, and email confirmations.
  expected_output: >
    Clear confirmation of scheduled appointments with details, or presentation 
    of alternative options if the requested time is unavailable.
  agent: appointment_scheduler_agent

treatment_guideline_task:
  description: |
    Provide treatment recommendations based on medical guidelines.

    Context from guidelines:
    {context}

    Base your answer ONLY on the context above. Include page references if available.
  expected_output: "Step-by-step treatment protocol with dosage, duration, and precautions."
  agent: treatment_guideline_agent

queue_monitoring_task:
  description: |
    Monitor patient queue and generate alerts for priority patients.
    Summarize queue status in real-time and highlight critical cases.
  expected_output: >
    Real-time queue status report.
  agent: queue_monitoring_agent

analytics_task:
  description: |
    Generate hospital analytics including patient flow, most common conditions, and KPIs.
    Provide a concise report ready for admin review.
  expected_output: >
    Dashboard-ready report for admin review.
  agent: analytics_agent

general_medical_task:
  description: |
    Answer general medical or health-related questions.
    Use the Medical Guidelines Retrieval Tool if relevant.
    If retrieval fails, provide an educational answer with a disclaimer.
  expected_output: >
    Clear, accurate, general medical explanation with disclaimer.
  agent: general_medical_agent
