symptom_check_task:
  description: |
    Analyze the following patient symptoms and suggest possible diagnoses based on medical guidelines.

    Context from medical knowledge base:
    {context}

    Use only the context above to answer. If unsure, say "Based on available guidelines, I cannot determine with certainty."
  expected_output: "List of possible conditions with likelihood indicators and supporting evidence from guidelines."
  agent: symptom_checker_agent

medical_history_task:
  description: |
    Retrieve patient medical history using the Patient Records Retrieval Tool.
    Use the patient_id if available. Summarize the most relevant medical records
    concisely and clearly for the user's query.
  expected_output: >
    Concise, readable answer for patient queries
  agent: medical_history_agent

appointment_booking_task:
  description: |
    Handle patient appointment booking requests using the N8n Appointment Booking Tool.
    
    When a patient requests to book an appointment, extract the following information:
    - Patient's email address
    - Desired appointment time (convert to ISO format like "2025-09-10T10:00")
    - Desired doctor's name
    - Patient's message about the appointment
    - Session ID for tracking
    
    Use the N8n Appointment Booking Tool to process the request. The tool will:
    - Check doctor availability for the requested time
    - Book the appointment if available
    - Provide alternative time slots if the requested time is unavailable
    
    Always provide a clear, helpful response to the patient including:
    - Confirmation of booking or explanation of unavailability
    - Available alternative time slots if needed
    - Next steps for the patient
  expected_output: >
    Clear confirmation of appointment booking status with available alternatives if needed,
    formatted in a patient-friendly manner.
  agent: appointment_scheduler_agent

treatment_guideline_task:
  description: |
    Provide treatment recommendations based on medical guidelines.

    Context from guidelines:
    {context}

    Base your answer ONLY on the context above. Include page references if available.
  expected_output: "Step-by-step treatment protocol with dosage, duration, and precautions."
  agent: treatment_guideline_agent

queue_monitoring_task:
  description: |
    Monitor patient queue and generate alerts for priority patients.
    Summarize queue status in real-time and highlight critical cases.
  expected_output: >
    Real-time queue status report.
  agent: queue_monitoring_agent

analytics_task:
  description: |
    Generate hospital analytics including patient flow, most common conditions, and KPIs.
    Provide a concise report ready for admin review.
  expected_output: >
    Dashboard-ready report for admin review.
  agent: analytics_agent

general_medical_task:
  description: |
    Answer general medical or health-related questions.
    Use the Medical Guidelines Retrieval Tool if relevant.
    If retrieval fails, provide an educational answer with a disclaimer.
  expected_output: >
    Clear, accurate, general medical explanation with disclaimer.
  agent: general_medical_agent
